# Week 12
## In-Class Activity

## Creating a `squirrel` DataFrame
>- Complete the following steps to practice reading in a csv file
>>- Note: You should download the `squirrel.csv` file from Canvas and save it in the same director/folder that you have this notebook saved in
1. Import the pandas module and alias it `pd`

### Step 1: Check your working directory and make sure you have the `squirrel.csv`  file there

In [1]:
pwd

'C:\\Users\\lukasz\\Desktop\\BAIM 3220 Python'

In [2]:
ls

 Volume in drive C is Windows
 Volume Serial Number is 8650-7A23

 Directory of C:\Users\lukasz\Desktop\BAIM 3220 Python

05/08/2021  08:09 AM    <DIR>          .
05/08/2021  08:09 AM    <DIR>          ..
05/08/2021  08:09 AM    <DIR>          .ipynb_checkpoints
04/17/2021  10:07 AM        15,349,323 complete.csv
04/20/2021  09:28 AM               485 customer.csv
04/21/2021  05:16 PM            49,774 foodplot4.png
03/30/2021  09:57 AM             3,837 Future50.csv
04/20/2021  09:28 AM               206 invoice.csv
04/01/2021  08:52 AM        33,633,170 JEOPARDY_CSV.csv
04/20/2021  09:28 AM               496 line.csv
04/13/2021  09:31 AM            38,013 loans.csv
03/30/2021  10:48 AM            54,263 Lukasz Stefanowicz Mar30_InClass.ipynb
04/17/2021  11:15 AM             5,761 LukaszStefanowiczQuiz3NEW.ipynb
04/29/2021  01:04 PM            20,726 ManipulatingStrings_TypeAlong_.ipynb
04/19/2021  03:40 PM         1,008,821 merged.ipynb
04/19/2021  03:39 PM                 0 'merged.ipynb'
04/19/2021  03:40 PM         1,007,775 merged2.ipynb
04/19/2021  03:42 PM         1,007,776 merged3.ipynb
04/19/2021  03:43 PM         1,007,776 merged4.ipynb
04/19/2021  03:45 PM         1,007,776 merged5.ipynb
04/19/2021  03:46 PM                 0 'merged5.ipynb'
04/13/2021  07:49 AM           154,182 MidtermReview.ipynb
04/13/2021  07:47 AM           162,212 MidtermReviewKey.ipynb
04/17/2021  10:46 AM                 0 -o
04/08/2021  09:32 AM           513,685 Panda Practice.ipynb
03/29/2021  04:39 PM           171,552 Panda Practice-Copy1.ipynb
04/29/2021  01:04 PM           154,383 Pandas_FindandReplace_TypeAlong_.ipynb
04/19/2021  12:31 PM           157,794 Pandas_FindandReplace_TypeAlongCOMPLETED.ipynb
04/29/2021  01:04 PM           192,151 Pandas_Part4_Grouping_TypeAlong_.ipynb
04/19/2021  03:41 PM           232,049 Pandas_Part4_Grouping_TypeAlongCOMPLETED.ipynb
04/29/2021  01:04 PM           176,008 Pandas_SumAggregateAndMapping_.ipynb
04/19/2021  03:41 PM           144,641 Pandas_SumAggregateAndMappingCOMPLETED.ipynb
04/29/2021  01:04 PM           205,209 Pandas2_Indexing-Selecting-Assigning_TypeAlong_.ipynb
04/12/2021  09:14 PM           198,946 Pandas2_Indexing-Selecting-Assigning_TypeAlongCOMPLETED.ipynb
04/29/2021  01:09 PM           783,353 Pandas6_CombiningData_TypeAlong_.ipynb
04/20/2021  09:25 AM           785,353 Pandas6_CombiningData_TypeAlongCompleted.ipynb
04/13/2021  07:42 AM            62,963 PandasIntro-TypeAlongMOSTLYDONESOMETHINGWRONG.ipynb
04/29/2021  01:04 PM            89,106 PandasIntro-TypeAlongNotebook_.ipynb
04/17/2021  10:45 AM                 0 'Pandasmergedapril.ipynb'
04/19/2021  12:33 PM                 0 'PandasMergedPart4and5'
04/19/2021  12:35 PM                 0 'PandasMergedPart4and5.ipynb'
04/22/2021  10:23 AM            14,637 PandasOnWikiData_TypeAlong.ipynb
04/29/2021  08:19 AM           212,292 PandasOnWikiData_TypeAlong_Completed.ipynb
04/13/2021  10:44 AM           349,333 PandasReview.ipynb
04/29/2021  01:04 PM           508,204 PandasReview_.ipynb
04/21/2021  05:16 PM            10,588 pieplot.png
04/19/2021  09:42 AM         4,839,076 Plant_1_Generation_Data.csv
04/19/2021  09:42 AM           287,847 Plant_1_Weather_Sensor_Data.csv
04/29/2021  01:04 PM            11,931 PracticeWithFunctions_typeAlong!.ipynb
04/20/2021  09:28 AM             1,164 product.csv
04/19/2021  03:46 PM            17,634 PythonBasics_TypeAlong.ipynb
04/21/2021  05:11 PM           304,053 sdfTester
03/30/2021  09:35 AM           720,589 squirrel.csv
04/22/2021  05:39 PM               872 state-abbrevs.csv
04/22/2021  05:39 PM               835 state-areas.csv
04/22/2021  05:46 PM            60,480 state-population.csv
04/13/2021  11:01 AM             5,229 Stefanowicz Lukasz Quiz 3.ipynb
04/13/2021  08:52 AM             8,744 Stefanowicz_Lukasz_hw4.ipynb
04/14/2021  08:59 AM             7,683 Stefanowicz_Lukasz_w2d1.ipynb
03/24/2021  11:08 AM            15,372 students100.xlsx
03/24/2021  11:08 AM            27,218 Top250.csv
04/12/2021  08:54 PM           542,107 topUS.csv
04/12/2021  08:54 PM           213,902 topUs.xlsx
03/29/2021  04:06 PM             2,197 Untitled.ipynb
04/19/2021  12:35 PM             1,835 Untitled1.ipynb
04/19/2021  01:06 PM            62,882 Untitled2.ipynb
04/19/2021  02:15 PM             1,221 Untitled3.ipynb
04/19/2021  02:17 PM               555 Untitled4.ipynb
04/22/2021  10:35 AM               690 Untitled5.ipynb
04/29/2021  09:06 AM            83,951 Untitled6.ipynb
04/20/2021  09:29 AM               570 vendor.csv
04/21/2021  05:41 PM            29,628 Week 15 practice.ipynb
04/20/2021  10:34 AM           209,545 Week15_VizTypeAlong.ipynb
04/22/2021  10:05 AM           577,168 Week15_VizTypeAlong_Completed.ipynb
03/29/2021  11:31 AM        52,796,676 winemag-data-130k-v2.csv
              72 File(s)    120,306,273 bytes
               3 Dir(s)  116,245,794,816 bytes free

### Step 2: import the `pandas` module and alias it `pd`

In [3]:
import numpy as np
import pandas as pd

### Step 3: Read the `squirrel.csv` file into a pandas dataframe named, `squ`
>- Look at the first five records to make sure `stu` is imported correctly

In [4]:
squ=pd.read_csv('squirrel.csv')
squ

,X,Y,Unique Squirrel ID,Hectare,Shift,Date,Hectare Squirrel Number,Age,Primary Fur Color,Highlight Fur Color,...,Kuks,Quaas,Moans,Tail flags,Tail twitches,Approaches,Indifferent,Runs from,Other Interactions,Lat/Long
0,-73.956134,40.794082,37F-PM-1014-03,37F,PM,10142018,3,NaN,NaN,NaN,...,False,False,False,False,False,False,False,False,NaN,POINT (-73.9561344937861 40.7940823884086)
1,-73.968857,40.783783,21B-AM-1019-04,21B,AM,10192018,4,NaN,NaN,NaN,...,False,False,False,False,False,False,False,False,NaN,POINT (-73.9688574691102 40.7837825208444)
2,-73.974281,40.775534,11B-PM-1014-08,11B,PM,10142018,8,NaN,Gray,NaN,...,False,False,False,False,False,False,False,False,NaN,POINT (-73.97428114848522 40.775533619083)
3,-73.959641,40.790313,32E-PM-1017-14,32E,PM,10172018,14,Adult,Gray,NaN,...,False,False,False,False,False,False,False,True,NaN,POINT (-73.9596413903948 40.7903128889029)
4,-73.970268,40.776213,13E-AM-1017-05,13E,AM,10172018,5,Adult,Gray,Cinnamon,...,False,False,False,False,False,False,False,False,NaN,POINT (-73.9702676472613 40.7762126854894)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3018,-73.963943,40.790868,30B-AM-1007-04,30B,AM,10072018,4,Adult,Gray,NaN,...,False,False,False,False,False,False,False,True,NaN,POINT (-73.9639431360458 40.7908677445466)
3019,-73.970402,40.782560,19A-PM-1013-05,19A,PM,10132018,5,Adult,Gray,White,...,False,False,False,False,False,False,True,False,NaN,POINT (-73.9704015859639 40.7825600069973)
3020,-73.966587,40.783678,22D-PM-1012-07,22D,PM,10122018,7,Adult,Gray,"Black, Cinnamon, White",...,False,False,False,False,False,False,True,False,NaN,POINT (-73.9665871993517 40.7836775064883)
3021,-73.963994,40.789915,29B-PM-1010-02,29B,PM,10102018,2,NaN,Gray,"Cinnamon, White",...,False,False,False,False,False,False,True,False,NaN,POINT (-73.9639941227864 40.7899152327912)
3022,-73.975479,40.769640,5E-PM-1012-01,05E,PM,10122018,1,Adult,Cinnamon,"Gray, White",...,False,False,False,False,False,True,False,False,NaN,POINT (-73.9754794191553 40.7696404489025)

#### Show the last five records of `squ`

In [5]:
squ.tail(5)

,X,Y,Unique Squirrel ID,Hectare,Shift,Date,Hectare Squirrel Number,Age,Primary Fur Color,Highlight Fur Color,...,Kuks,Quaas,Moans,Tail flags,Tail twitches,Approaches,Indifferent,Runs from,Other Interactions,Lat/Long
3018,-73.963943,40.790868,30B-AM-1007-04,30B,AM,10072018,4,Adult,Gray,NaN,...,False,False,False,False,False,False,False,True,NaN,POINT (-73.9639431360458 40.7908677445466)
3019,-73.970402,40.782560,19A-PM-1013-05,19A,PM,10132018,5,Adult,Gray,White,...,False,False,False,False,False,False,True,False,NaN,POINT (-73.9704015859639 40.7825600069973)
3020,-73.966587,40.783678,22D-PM-1012-07,22D,PM,10122018,7,Adult,Gray,"Black, Cinnamon, White",...,False,False,False,False,False,False,True,False,NaN,POINT (-73.9665871993517 40.7836775064883)
3021,-73.963994,40.789915,29B-PM-1010-02,29B,PM,10102018,2,NaN,Gray,"Cinnamon, White",...,False,False,False,False,False,False,True,False,NaN,POINT (-73.9639941227864 40.7899152327912)
3022,-73.975479,40.769640,5E-PM-1012-01,05E,PM,10122018,1,Adult,Cinnamon,"Gray, White",...,False,False,False,False,False,True,False,False,NaN,POINT (-73.9754794191553 40.7696404489025)

#### Show a tuple of the number of columns and rows in `squ`

In [6]:
squ.shape

(3023, 31)

#### Show the columns in `squ`

In [7]:
squ.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3023 entries, 0 to 3022
Data columns (total 31 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   X                                           3023 non-null   float64
 1   Y                                           3023 non-null   float64
 2   Unique Squirrel ID                          3023 non-null   object
 3   Hectare                                     3023 non-null   object
 4   Shift                                       3023 non-null   object
 5   Date                                        3023 non-null   int64
 6   Hectare Squirrel Number                     3023 non-null   int64
 7   Age                                         2902 non-null   object
 8   Primary Fur Color                           2968 non-null   object
 9   Highlight Fur Color                         1937 non-null   object
 10  Combination of Primary and Highlight Color  3023 non-null   object
 11  Color notes                                 182 non-null    object
 12  Location                                    2959 non-null   object
 13  Above Ground Sighter Measurement            2909 non-null   object
 14  Specific Location                           476 non-null    object
 15  Running                                     3023 non-null   bool
 16  Chasing                                     3023 non-null   bool
 17  Climbing                                    3023 non-null   bool
 18  Eating                                      3023 non-null   bool
 19  Foraging                                    3023 non-null   bool
 20  Other Activities                            437 non-null    object
 21  Kuks                                        3023 non-null   bool
 22  Quaas                                       3023 non-null   bool
 23  Moans                                       3023 non-null   bool
 24  Tail flags                                  3023 non-null   bool
 25  Tail twitches                               3023 non-null   bool
 26  Approaches                                  3023 non-null   bool
 27  Indifferent                                 3023 non-null   bool
 28  Runs from                                   3023 non-null   bool
 29  Other Interactions                          240 non-null    object
 30  Lat/Long                                    3023 non-null   object
dtypes: bool(13), float64(2), int64(2), object(14)
memory usage: 463.6+ KB

#### Show the datatypes that are in `squ`

In [8]:
squ.dtypes

X                                             float64
Y                                             float64
Unique Squirrel ID                             object
Hectare                                        object
Shift                                          object
Date                                            int64
Hectare Squirrel Number                         int64
Age                                            object
Primary Fur Color                              object
Highlight Fur Color                            object
Combination of Primary and Highlight Color     object
Color notes                                    object
Location                                       object
Above Ground Sighter Measurement               object
Specific Location                              object
Running                                          bool
Chasing                                          bool
Climbing                                         bool
Eating                                           bool
Foraging                                         bool
Other Activities                               object
Kuks                                             bool
Quaas                                            bool
Moans                                            bool
Tail flags                                       bool
Tail twitches                                    bool
Approaches                                       bool
Indifferent                                      bool
Runs from                                        bool
Other Interactions                             object
Lat/Long                                       object
dtype: object

### Show a list of the unique 'Primary Fur Color' values

### Show how many unique 'Primary Fur Color' values there

In [9]:
len(squ['Primary Fur Color'].unique())

4

### Based on a descriptive analytics table for `squ`, what was the top Primary Fur Color?

In [10]:
squ['Primary Fur Color'].describe()

count     2968
unique       3
top       Gray
freq      2473
Name: Primary Fur Color, dtype: object

### Add a new column` Tail Flags/Twitches` to `squ` that stores the result of Tail flags/Tail twitches.

In [11]:
squ['Hectare Squared']=squ[['Hectare Squirrel Number']].applymap(np.square)

### Show me the dataframe with the new column added

In [12]:
squ

,X,Y,Unique Squirrel ID,Hectare,Shift,Date,Hectare Squirrel Number,Age,Primary Fur Color,Highlight Fur Color,...,Quaas,Moans,Tail flags,Tail twitches,Approaches,Indifferent,Runs from,Other Interactions,Lat/Long,Hectare Squared
0,-73.956134,40.794082,37F-PM-1014-03,37F,PM,10142018,3,NaN,NaN,NaN,...,False,False,False,False,False,False,False,NaN,POINT (-73.9561344937861 40.7940823884086),9
1,-73.968857,40.783783,21B-AM-1019-04,21B,AM,10192018,4,NaN,NaN,NaN,...,False,False,False,False,False,False,False,NaN,POINT (-73.9688574691102 40.7837825208444),16
2,-73.974281,40.775534,11B-PM-1014-08,11B,PM,10142018,8,NaN,Gray,NaN,...,False,False,False,False,False,False,False,NaN,POINT (-73.97428114848522 40.775533619083),64
3,-73.959641,40.790313,32E-PM-1017-14,32E,PM,10172018,14,Adult,Gray,NaN,...,False,False,False,False,False,False,True,NaN,POINT (-73.9596413903948 40.7903128889029),196
4,-73.970268,40.776213,13E-AM-1017-05,13E,AM,10172018,5,Adult,Gray,Cinnamon,...,False,False,False,False,False,False,False,NaN,POINT (-73.9702676472613 40.7762126854894),25
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3018,-73.963943,40.790868,30B-AM-1007-04,30B,AM,10072018,4,Adult,Gray,NaN,...,False,False,False,False,False,False,True,NaN,POINT (-73.9639431360458 40.7908677445466),16
3019,-73.970402,40.782560,19A-PM-1013-05,19A,PM,10132018,5,Adult,Gray,White,...,False,False,False,False,False,True,False,NaN,POINT (-73.9704015859639 40.7825600069973),25
3020,-73.966587,40.783678,22D-PM-1012-07,22D,PM,10122018,7,Adult,Gray,"Black, Cinnamon, White",...,False,False,False,False,False,True,False,NaN,POINT (-73.9665871993517 40.7836775064883),49
3021,-73.963994,40.789915,29B-PM-1010-02,29B,PM,10102018,2,NaN,Gray,"Cinnamon, White",...,False,False,False,False,False,True,False,NaN,POINT (-73.9639941227864 40.7899152327912),4
3022,-73.975479,40.769640,5E-PM-1012-01,05E,PM,10122018,1,Adult,Cinnamon,"Gray, White",...,False,False,False,False,True,False,False,NaN,POINT (-73.9754794191553 40.7696404489025),1